version: '3.8'

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres

        volumes:
            - postgres:/data/postgres
            - ./src/main/psql/:/docker-entrypoint-initdb.d/
        networks:
            - postgres
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
            PGADMIN_DEFAULT_PASSWORD: "admin"
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_LISTEN_PORT: 5050
        volumes:
            - ./pgadmindata:/root/.pgadmin
        ports:
            - 5050:5050
        networks:
            - postgres

    vertx-app:
        image: vertx-app:latest
        # build: ./build/libs/
        # command: java -jar CS386-1.0.0-SNAPSHOT-fat.jar
        ports:
            - 8888:8888
        depends_on:
            -   postgres
        networks:
            - postgres
networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmindata:
