Deliverable 5
Section 5

Subsection 1
	Creational Design Patterns
	Singleton: Ensures only one instance of an object is created.(1)
	![](d5singletonPattern.png)
	Pulp:           https://github.com/Csaluski/cs-386-project/blob/main/src/main/java/edu/nau/cs386/Pulp.java
	UserManager:    https://github.com/Csaluski/cs-386-project/blob/main/src/main/java/edu/nau/cs386/manager/UserManager.java
	UserPaper:      https://github.com/Csaluski/cs-386-project/blob/main/src/main/java/edu/nau/cs386/manager/PaperManager.java

Subsection 2
    Structural Design Pattern
	Façade: Provides a simple interface to a more complex underlying object.(1)
	![](Deliverable5Section5Subsection2.png)
	DatabaseDriver: https://github.com/Csaluski/cs-386-project/blob/main/src/main/java/edu/nau/cs386/database/DatabaseDriver.java
	UserManager:    https://github.com/Csaluski/cs-386-project/blob/main/src/main/java/edu/nau/cs386/manager/UserManager.java
	UserPaper:      https://github.com/Csaluski/cs-386-project/blob/main/src/main/java/edu/nau/cs386/manager/PaperManager.java

Citation:
(1) Gamma, E., Helm, R., Johnson, R., & Vlissides, J. (2019, May 21). Gang of Four Design Patterns. Spring Framework
    Guru. https://springframework.guru/gang-of-four-design-patterns/.

