@startuml
'https://plantuml.com/class-diagram
'3'
class WordProcessorCommand
class Caller
class Client
class Reciever
class UNDO{
Pop()
Push()
}
class REDO{
Pop()
Push()
}
class UNDO implements Reciever
class REDO implements Reciever
Caller *--> Command
WordProcessorCommand --|> Command
WordProcessorCommand --> Reciever
Client -> WordProcessorCommand
Client --> Reciever


@enduml
